CREATE TABLE IF NOT EXISTS EXCHANGE_RATE(
	ID INTEGER NOT NULL,
	DATE DATE NOT NULL,
	BASE_CURRENCY VARCHAR(3) NOT NULL,
	TARGET_CURRENCY VARCHAR(3) NOT NULL,
	RATE DOUBLE NOT NULL,
	PRIMARY KEY(DATE, BASE_CURRENCY, TARGET_CURRENCY)
);

CREATE TABLE IF NOT EXISTS CURRENCY(
	ID INTEGER PRIMARY KEY NOT NULL,
	NAME VARCHAR(3) UNIQUE NOT NULL
);